// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Admission_test_registration
{
    public partial class ExamGradePredictor
    {
        /// <summary>
        /// model input class for ExamGradePredictor.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Sex")]
            public string Sex { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Math_Grade")]
            public float Math_Grade { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"History_Grade")]
            public float History_Grade { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"English_Grade")]
            public float English_Grade { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Social_Activity")]
            public bool Social_Activity { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Science_Competition_Activity")]
            public bool Science_Competition_Activity { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Sport_Activity")]
            public bool Sport_Activity { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"University Entrance Exam Grade")]
            public float University_Entrance_Exam_Grade { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ExamGradePredictor.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Sex")]
            public float[] Sex { get; set; }

            [ColumnName(@"Math_Grade")]
            public float Math_Grade { get; set; }

            [ColumnName(@"History_Grade")]
            public float History_Grade { get; set; }

            [ColumnName(@"English_Grade")]
            public float English_Grade { get; set; }

            [ColumnName(@"Social_Activity")]
            public float[] Social_Activity { get; set; }

            [ColumnName(@"Science_Competition_Activity")]
            public float[] Science_Competition_Activity { get; set; }

            [ColumnName(@"Sport_Activity")]
            public float[] Sport_Activity { get; set; }

            [ColumnName(@"University Entrance Exam Grade")]
            public float University_Entrance_Exam_Grade { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ExamGradePredictor.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
